# Generated by Django 4.1.3 on 2022-11-25 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('softdesk_api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_id',
        ),
    ]
